# Generated by Django 5.2.17 on 2026-08-14 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world_politics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='capital',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='country',
            name='continent',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='country',
            name='government_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
