# Generated by Django 5.2.17 on 2026-08-14 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world_politics', '0002_country_capital_country_continent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='continent',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.CreateModel(
            name='CountryProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('history', models.TextField(blank=True)),
                ('country', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='world_politics.country')),
            ],
        ),
    ]
