# Generated by Django 5.2.17 on 2026-08-14 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world_politics', '0003_alter_country_continent_countryprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterestingFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fact', models.TextField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interesting_facts', to='world_politics.country')),
            ],
        ),
    ]
