# Generated by Django 5.2.17 on 2026-08-14 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world_politics', '0006_politicalparty'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoliticalLeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('position', models.CharField(max_length=150)),
                ('dat_of_birth', models.DateField(blank=True, null=True)),
                ('biography', models.TextField(blank=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='political_leaders', to='world_politics.country')),
                ('party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leaders', to='world_politics.politicalparty')),
            ],
        ),
    ]
