# Generated by Django 5.2.17 on 2026-08-14 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world_politics', '0008_election'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votes', models.PositiveIntegerField(default=0)),
                ('seats_won', models.PositiveIntegerField(default=0)),
                ('elections', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='world_politics.election')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='election_results', to='world_politics.politicalparty')),
            ],
        ),
    ]
