# Generated by Django 5.2.17 on 2026-08-14 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world_politics', '0009_electionresult'),
    ]

    operations = [
    migrations.RenameField(
        model_name="electionresult",
        old_name="elections",
        new_name="election",
    ),
]