# Generated by Django 5.2.17 on 2026-08-14 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world_politics', '0010_rename_elections_to_election'),
    ]

    operations = [
        migrations.RenameField(
            model_name='politicalparty',
            old_name='founded_data',
            new_name='founded_date',
        ),
        migrations.AlterField(
            model_name='electionresult',
            name='election',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='world_politics.election'),
        ),
    ]
