# Generated by Django 5.2.17 on 2026-08-15 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world_politics', '0012_country_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='politicalparty',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='party_logos/'),
        ),
    ]
