# Generated by Django 5.2.17 on 2026-08-15 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world_politics', '0013_politicalparty_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='politicalleader',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='leaders/'),
        ),
    ]
