# Generated by Django 5.2.17 on 2026-08-23 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world_politics', '0014_politicalleader_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='politicalleader',
            name='term_end',
            field=models.CharField(blank=True, help_text='End year/date of term (e.g. 2019 or Present)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='politicalleader',
            name='term_start',
            field=models.CharField(blank=True, help_text='Start year/date of term (e.g. 2014 or May 2014)', max_length=100, null=True),
        ),
    ]
