# Generated by Django 5.2.15 on 2026-09-06 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world_politics', '0015_politicalleader_term_end_politicalleader_term_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Geographic center latitude for globe marker', null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Geographic center longitude for globe marker', null=True),
        ),
    ]
